<a href="https://colab.research.google.com/github/aga-moj-nick/data-science-bootcamp-w-py/blob/main/01_wprowadzenie/01_numpy_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

--* @author: krakowiakpawel9@gmail.com  
* @site: e-smartdata.org

### NumPy
>Strona biblioteki: [https://numpy.org/](https://numpy.org/)  
>Dokumentacja: [https://numpy.org/doc/](https://numpy.org/doc/)  
>
>Podstawowa biblioteka do obliczeń numerycznych w języku Python.
>
>Aby zainstalować bibliotekę NumPy, użyj polecenia poniżej:
```
pip install numpy
```

### Spis treści:
1. [Podstawy](#a1)
2. [Typy danych](#a2)
3. [Tworzenie tablic](#a3)
4. [Podstawowe operacje na tablicach](#a4)
5. [Generowanie liczb pseudolosowych](#a5)
6. [Podstawowe funkcje](#a6)
7. [Indeksowanie, Wycinanie](#a7)
8. [Iteracja po tablicach](#a8)
9. [Zmiana rozmiaru tablic](#a9)
10. [Maski logiczne](#a10)


### <a name='a1'></a> Podstawy

In [1]:
import numpy as np
np.__version__

'1.22.4'

In [ ]:
print(dir(np))


In [ ]:
import numpy as np
np.__version__

'1.17.4'

In [ ]:
print(dir(np))

In [ ]:
help(np.array)

In [ ]:
help(np.array)

1D Array

In [5]:
x = np.array([1, 3])
x

array([1, 3])

In [ ]:
x = np.array([1, 3])
x

array([1, 3])

In [6]:
print(x)

[1 3]


In [ ]:
print(x)

[1 3]


In [7]:
type(x)

numpy.ndarray

In [8]:
x.ndim

1

In [ ]:
x.ndim

1

In [9]:
x.shape

(2,)

In [10]:
x.size

2

In [11]:
x.dtype

dtype('int64')

In [14]:
x = np.array([1.3, 2.3, 1.4])
print(x)

[1.3 2.3 1.4]


In [ ]:
x.dtype

dtype('float64')

In [15]:
x = np.array([1.3, 2.3, 1.4])
print(x)

[1.3 2.3 1.4]


In [66]:
x.dtype

dtype('int64')

2D Array

In [20]:
x = np.array([[1, 2], [-3, 1]])
x

array([[ 1,  2],
       [-3,  1]])

In [21]:
x.ndim

2

In [22]:
x.shape

(2, 2)

In [23]:
x = np.array([[1, 2, 4], [4, 2, 1]])
print(x)

[[1 2 4]
 [4 2 1]]


In [24]:
x.shape

(2, 3)

3D Array

In [25]:
x = np.array(
    [[[4, 3, 1],
      [3, 1, 2]],
     
     [[4, 1, 3],
      [4, 2, 1]],
     
     [[3, 2, 1],
      [4, 3, 2]]]
)
x

array([[[4, 3, 1],
        [3, 1, 2]],

       [[4, 1, 3],
        [4, 2, 1]],

       [[3, 2, 1],
        [4, 3, 2]]])

In [26]:
x.ndim

3

In [27]:
x.shape

(3, 2, 3)

In [28]:
x = np.array(
    [[[4, 3, 1],
      [3, 1, 2]],
     
     [[4, 1, 3],
      [4, 2, 1]],
     
     [[3, 2, 1],
      [4, 3, 2]]]
)
print(x)

[[[4 3 1]
  [3 1 2]]

 [[4 1 3]
  [4 2 1]]

 [[3 2 1]
  [4 3 2]]]


### <a name='a2'></a> Typy danych

In [29]:
A = np.array([1, 2, 3])
A.dtype

dtype('int64')

In [30]:
A = np.array([1.0, 2.3, 3.3])
A.dtype

dtype('float64')

In [63]:
A = np.array([1, 2, 3], dtype='float')
A.dtype

dtype('float64')

In [67]:
A = np.array(['ala', 'ma', 'kota'], dtype='string')
A.dtype

TypeError: ignored

In [36]:
A = np.array([1, 2, 3], dtype='complex')
A.dtype

dtype('complex128')

In [37]:
A = np.array([1.0, 2.7, 3.3], dtype='int')
A.dtype

dtype('int64')

In [38]:
A

array([1, 2, 3])

In [39]:
A = np.array([True, False])
A.dtype

dtype('bool')

In [40]:
A = np.array([24, 120, 230], dtype=np.int8)
A.dtype

dtype('int8')

In [41]:
A = np.array([24, 120, 230], dtype=np.uint8)
A.dtype

dtype('uint8')

### <a name='a3'></a> Tworzenie tablic

In [42]:
np.zeros(shape=(4, 10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [43]:
np.zeros(shape=(10, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [44]:
np.zeros(shape=(4, 10), dtype='int')

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [45]:
np.zeros(shape=(10, 4), dtype='int')

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [47]:
np.ones(shape=(5, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [48]:
np.ones(shape=(5, 5), dtype='int')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [49]:
np.full(shape=(3, 3), fill_value=4, dtype='int')

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [50]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [53]:
np.arange(start=5, stop=10)

array([5, 6, 7, 8, 9])

In [54]:
np.arange(start=20, stop=75)

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
       54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70,
       71, 72, 73, 74])

In [55]:
np.arange(start=10, stop=100, step=10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [57]:
np.arange(start=1, stop=30, step=3)

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28])

In [ ]:
np.arange(start=100, stop=10, step=-10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

In [58]:
np.arange(start=30, stop=1, step=-3)

array([30, 27, 24, 21, 18, 15, 12,  9,  6,  3])

In [ ]:
np.arange(start=0, stop=1, step=0.05)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [59]:
np.arange(start=1, stop=10, step=2.5)

array([1. , 3.5, 6. , 8.5])

In [ ]:
np.linspace(start=0, stop=1, num=11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [69]:
np.linspace(start=1, stop=30, num=3)

array([ 1. , 15.5, 30. ])

array([ 1. , 15.5, 30. ])

In [71]:
A = np.arange(15)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [72]:
A.reshape((3, 5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [73]:
A.reshape((5, 3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [ ]:
A.reshape((3, -1))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [74]:
A.reshape((5, -1))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [ ]:
A.reshape((-1, 3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [75]:
A.reshape((5, -1))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

### <a name='a4'></a> Podstawowe operacje na tablicach

In [76]:
A = np.array([3, 1, 4, 2])
B = np.array([3, -1, 3, 2])
print(A)
print(B)

[3 1 4 2]
[ 3 -1  3  2]


In [77]:
A + B

array([6, 0, 7, 4])

In [80]:
A - B

array([0, 2, 1, 0])

In [81]:
A * B

array([ 9, -1, 12,  4])

In [82]:
A / B

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [83]:
A + 3

array([6, 4, 7, 5])

In [85]:
A - 1

array([2, 0, 3, 1])

In [86]:
A * 2

array([6, 2, 8, 4])

In [87]:
A/2

array([1.5, 0.5, 2. , 1. ])

In [88]:
A + 3 * B

array([12, -2, 13,  8])

In [89]:
np.add(A, B)

array([6, 0, 7, 4])

In [93]:
np.add(B, A)

array([6, 0, 7, 4])

In [90]:
np.subtract(A, B)

array([0, 2, 1, 0])

In [96]:
np.subtract(B, A)

array([ 0, -2, -1,  0])

In [91]:
np.multiply(A, B)

array([ 9, -1, 12,  4])

In [92]:
np.divide(A, B)

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [95]:
np.divide(B, A)

array([ 1.  , -1.  ,  0.75,  1.  ])

In [ ]:
A + 3

array([6, 4, 7, 5])

In [ ]:
2 * A

array([6, 2, 8, 4])

In [ ]:
A + 3*B

array([12, -2, 13,  8])

In [97]:
X = np.array([[1, 3], [-2, 0]])
Y = np.array([[6, 0], [-1, 2]])
print(X, '\n')
print(Y)

[[ 1  3]
 [-2  0]] 

[[ 6  0]
 [-1  2]]


In [98]:
X * Y

array([[6, 0],
       [2, 0]])

In [99]:
np.dot(X, Y)

array([[  3,   6],
       [-12,   0]])

In [100]:
np.dot(Y, X)

array([[ 6, 18],
       [-5, -3]])

In [101]:
X.dot(Y)

array([[  3,   6],
       [-12,   0]])

In [102]:
Y.dot(X)

array([[ 6, 18],
       [-5, -3]])

In [103]:
X @ Y

array([[  3,   6],
       [-12,   0]])

### <a name='a5'></a>  Generowanie liczb pseudolosowych

In [104]:
np.random.seed(0)

In [105]:
np.random.randn()

1.764052345967664

In [106]:
np.random.randn(10)

array([ 0.40015721,  0.97873798,  2.2408932 ,  1.86755799, -0.97727788,
        0.95008842, -0.15135721, -0.10321885,  0.4105985 ,  0.14404357])

In [107]:
np.random.randn(100)

array([ 1.45427351,  0.76103773,  0.12167502,  0.44386323,  0.33367433,
        1.49407907, -0.20515826,  0.3130677 , -0.85409574, -2.55298982,
        0.6536186 ,  0.8644362 , -0.74216502,  2.26975462, -1.45436567,
        0.04575852, -0.18718385,  1.53277921,  1.46935877,  0.15494743,
        0.37816252, -0.88778575, -1.98079647, -0.34791215,  0.15634897,
        1.23029068,  1.20237985, -0.38732682, -0.30230275, -1.04855297,
       -1.42001794, -1.70627019,  1.9507754 , -0.50965218, -0.4380743 ,
       -1.25279536,  0.77749036, -1.61389785, -0.21274028, -0.89546656,
        0.3869025 , -0.51080514, -1.18063218, -0.02818223,  0.42833187,
        0.06651722,  0.3024719 , -0.63432209, -0.36274117, -0.67246045,
       -0.35955316, -0.81314628, -1.7262826 ,  0.17742614, -0.40178094,
       -1.63019835,  0.46278226, -0.90729836,  0.0519454 ,  0.72909056,
        0.12898291,  1.13940068, -1.23482582,  0.40234164, -0.68481009,
       -0.87079715, -0.57884966, -0.31155253,  0.05616534, -1.16

In [ ]:
np.random.randn(10, 4)

array([[ 1.45427351,  0.76103773,  0.12167502,  0.44386323],
       [ 0.33367433,  1.49407907, -0.20515826,  0.3130677 ],
       [-0.85409574, -2.55298982,  0.6536186 ,  0.8644362 ],
       [-0.74216502,  2.26975462, -1.45436567,  0.04575852],
       [-0.18718385,  1.53277921,  1.46935877,  0.15494743],
       [ 0.37816252, -0.88778575, -1.98079647, -0.34791215],
       [ 0.15634897,  1.23029068,  1.20237985, -0.38732682],
       [-0.30230275, -1.04855297, -1.42001794, -1.70627019],
       [ 1.9507754 , -0.50965218, -0.4380743 , -1.25279536],
       [ 0.77749036, -1.61389785, -0.21274028, -0.89546656]])

In [108]:
np.random.randn(100, 10)

array([[ 9.06044658e-01, -8.61225685e-01,  1.91006495e+00,
        -2.68003371e-01,  8.02456396e-01,  9.47251968e-01,
        -1.55010093e-01,  6.14079370e-01,  9.22206672e-01,
         3.76425531e-01],
       [-1.09940079e+00,  2.98238174e-01,  1.32638590e+00,
        -6.94567860e-01, -1.49634540e-01, -4.35153552e-01,
         1.84926373e+00,  6.72294757e-01,  4.07461836e-01,
        -7.69916074e-01],
       [ 5.39249191e-01, -6.74332661e-01,  3.18305583e-02,
        -6.35846078e-01,  6.76433295e-01,  5.76590817e-01,
        -2.08298756e-01,  3.96006713e-01, -1.09306151e+00,
        -1.49125759e+00],
       [ 4.39391701e-01,  1.66673495e-01,  6.35031437e-01,
         2.38314477e+00,  9.44479487e-01, -9.12822225e-01,
         1.11701629e+00, -1.31590741e+00, -4.61584605e-01,
        -6.82416053e-02],
       [ 1.71334272e+00, -7.44754822e-01, -8.26438539e-01,
        -9.84525244e-02, -6.63478286e-01,  1.12663592e+00,
        -1.07993151e+00, -1.14746865e+00, -4.37820045e-01,
        -4.

In [109]:
np.random.rand()

0.88118825140944

In [110]:
np.random.rand(10)

array([0.91641901, 0.2715511 , 0.60754536, 0.52658403, 0.53794578,
       0.93766309, 0.3051887 , 0.98343398, 0.90213121, 0.45872289])

In [111]:
np.random.rand(10, 2)

array([[0.81745326, 0.76904699],
       [0.67789497, 0.31983389],
       [0.19645099, 0.6715277 ],
       [0.8429733 , 0.01625279],
       [0.64280338, 0.44287302],
       [0.89808776, 0.32147293],
       [0.47418481, 0.5147671 ],
       [0.14043952, 0.7128923 ],
       [0.83047635, 0.05790928],
       [0.29138882, 0.03804468]])

In [113]:
np.random.randint(10)

1

In [114]:
np.random.randint(low=10, high=101)

39

In [115]:
np.random.randint(low=10, high=101, size=10)

array([ 73,  71,  93, 100,  36,  83,  60,  27,  81,  66])

In [116]:
np.random.choice([4, 2, 1, 3, 5])

3

In [119]:
np.random.choice(['python', 'java', 'sql'])

'python'

In [120]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [123]:
np.random.shuffle(data)

In [124]:
data

array([5, 9, 3, 6, 8, 1, 0, 2, 7, 4])

### <a name='a6'></a> Podstawowe funkcje

Exponent - popularna w sieciach neuronowych i uczeniu maszynowym.

Jeśli podniesiemy do 1, jest to stała Eulera:

In [125]:
np.exp(1)

2.718281828459045

In [126]:
np.exp(10)

22026.465794806718

In [127]:
np.exp(-2)

0.1353352832366127

Pierwiastek kwadratowy z przekazanej liczby (zwróci ją w typie float):

In [128]:
np.sqrt(9)

3.0

In [129]:
np.sqrt(100)

10.0

Funkcje logiczne, które testują, co znajduje się w naszych listach lub tablicach:


In [131]:
np.all([2, 3, 1])

True

In [132]:
np.all([0, 1, 2])

False

All: przechodzi po naszym obiekcie iterowalnym i bada, czy każdy element zwraca wartość logiczną False czy True. Jeżeli każda wartość zwróci prawdę, to zwróci prawdę. Jeżeli którakolwiek z tych wartości zwróci fałsz, to funkcja all zwróci False. To nie musi być lista pythonowa, to może być obiekt array.

In [133]:
np.any([0, 0, 0])

False

In [134]:
np.any([0, 1, 0])

True

Any - sprawdza, czy jakikolwiek obiekt jest prawdą. Zwróci prawdę, jeśli choć jeden będzie prawdą. Jeśli wszystkie będą false, to wtedy zwróci false. Zastosowanie: jeśli mamy dużą tablicę, która składa się głównie z 0 i są pojedyncze 1, to możemy właśnie funkcją any szybko to sprawdzić.

In [135]:
bool(1.3)

True

W przypadku 0 zwraca False, w przypadku każdej innej liczby zwraca True.

**Statystyczne:**

In [137]:
A = np.random.randn(5)
A

array([ 1.25916713, -1.03760694, -0.14690506,  0.43111328,  0.71923033])

Generowanie małego obiektu, na którym będziemy pracować - funkcja, która generuje wartości z rozkładu normalnego randn.

In [141]:
A = np.random.rand(5)
A

array([0.08695535, 0.93087704, 0.69439389, 0.77824173, 0.79161454])

rand - wartości z rozkładu jednostajnego, wartości w przedziale 0-1. Np. prawdopodobieństwa otrzymania klasy dla danej próbki. Problem klasyfikacji, pięć klas i chcemy którąś klasę przyporządkować. Model zwrócił wartości prawdopodobieństw i chcielibyśmy coś zrobić.

Chcemy użyć funkcji, która wyciągnie indeks, gdzie nasza tablica przyjmuje największą wartość: 

In [142]:
np.argmax(A)

1

Jeśli chcemy wyciąć tę wartość z tablicy:

In [143]:
A[np.argmax(A)]

0.930877036418403

Jest też funkcja, która pokaże indeks wartości najniższej:

In [145]:
np.argmin(A)

0

Ją też można wyciąć:

In [146]:
A[np.argmin(A)]

0.08695534603725286

Funkcja użyteczna przy klasyfikacji wieloklasowej. Pozwala sortować elementy, podając odpowiednio indeks od najmniejszej wartości do największej:

In [147]:
np.argsort(A)

array([0, 2, 3, 4, 1])

**Funkcje czysto statystyczne:**

Maximum = zwracamy wartość najwyższą

In [148]:
np.max(A)

0.930877036418403

Minimum = wartość najniższa

In [149]:
np.min(A)

0.08695534603725286

Średnia arytmetyczna:

In [151]:
np.mean(A)

0.6564165072744746

Mediana:

In [152]:
np.median(A)

0.7782417274338482

SD:

In [153]:
np.std(A)

0.2946783906031805

###  <a name='a7'></a> Indeksowanie, Wycinanie

Generowanie danych, za pomocą których będziemy pracować. Generowanie tablicy jednowymiarowej, która zawiera 20 elementów:

In [154]:
A = np.arange(20)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

Wycinanie podobne do tego w PY. Podajemy nawias kwadratowy i takie atrybuty jak: 
A[idx] = indeks, który chcemy wyciąć. W Py zaczynamy indeksować od 0. Można podać konkretny nr indeksu
A[start:stop] = można podać konkretny przedział indeksu, czyli indeks startowy i końcowy
a[:stop] lub A[start:] = można podać konkretny indeks, na którym chcemy skończyć lub konkretny indeks, od którego chcemy zacząć


In [ ]:
# A[idx], A[start:stop], A[:stop], A[start:]

In [155]:
A[2]

2

In [159]:
A[5]

5

In [156]:
A[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [160]:
A[6:]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [157]:
A[:2]

array([0, 1])

In [161]:
A[:5]

array([0, 1, 2, 3, 4])

In [ ]:
A[[0, 2]]

array([0, 2])

In [158]:
A[[0, 5]]

array([0, 5])

In [ ]:
A[-1]

19

In [162]:
A[-3]

17

In [ ]:
A[10:15]

array([10, 11, 12, 13, 14])

In [163]:
A[13:20]

array([13, 14, 15, 16, 17, 18, 19])

Przekształcanie tablicy metodą reshape

In [167]:
A = A.reshape(4, 5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

Wycinanie danych z tablicy:

In [168]:
A[1]

array([5, 6, 7, 8, 9])

Wycinanie kolumny:
A[:, 0]
Pierwszy parametr - dwukropek, drugi - indeks kolumny

In [169]:
A[:, 0]

array([ 0,  5, 10, 15])

In [170]:
A[:, 1]

array([ 1,  6, 11, 16])

In [171]:
A[:, 2]

array([ 2,  7, 12, 17])

In [172]:
A[:, 3]

array([ 3,  8, 13, 18])

In [173]:
A[:, 4]

array([ 4,  9, 14, 19])

In [174]:
A[:, -1]

array([ 4,  9, 14, 19])

In [176]:
A[1, 3]

8

Możemy wycinać fragmenty kolumny:

In [178]:
A[0:3, 2:4]

array([[ 2,  3],
       [ 7,  8],
       [12, 13]])

In [ ]:
A[1:3, 1:4]

array([[ 6,  7,  8],
       [11, 12, 13]])

Najpierw wycinamy 7, a później przypisujemy do niej 14 i wyświtlamy całą tablicę:

In [179]:
A[1, 2]

7

In [ ]:
A[1, 2] = 14
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [181]:
A[2, 1] = 10
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 10, 12, 13, 14],
       [15, 16, 17, 18, 19]])

### <a name='a8'></a> Iteracja po tablicach

Tablica dwuwymiarowa:

In [182]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 10, 12, 13, 14],
       [15, 16, 17, 18, 19]])

Iterowanie po wierszu:

In [183]:
for row in A:
    print(row)

[0 1 2 3 4]
[5 6 7 8 9]
[10 10 12 13 14]
[15 16 17 18 19]


In [186]:
for row in A:
  print(row)

[0 1 2 3 4]
[5 6 7 8 9]
[10 10 12 13 14]
[15 16 17 18 19]


In [184]:
for row in A:
    print(row[:3])

[0 1 2]
[5 6 7]
[10 10 12]
[15 16 17]


In [187]:
for row in A:
  print(row[:1])

[0]
[5]
[10]
[15]


Iterowanie po każdym elemencie. Do tego potrzebny atrybut flat:

In [189]:
for item in A.flat:
    print(item)

0
1
2
3
4
5
6
7
8
9
10
10
12
13
14
15
16
17
18
19


### <a name='a9'></a> Zmiana rozmiaru tablic

In [ ]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

Tablica wymiaru 4x5, o czym możemy sobie przypomnieć metodą shape:

In [190]:
A.shape

(4, 5)

Metoda reshape - można za jej pomocą zmienić rozmiar tablicy

In [191]:
A.reshape(5, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 10],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [192]:
A.reshape(4, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 10, 12, 13, 14],
       [15, 16, 17, 18, 19]])

Metoda ravel pozwala wypłaszczyć dane, powrót do płaskiej postaci

In [193]:
A.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 10, 12, 13, 14, 15, 16,
       17, 18, 19])

Transponowanie tablicy odbywa się tak samo jak transponowanie macierzy, czyli zamieniamy wierz na kolumnę, kolumnę na wiersz

In [ ]:
A.T

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2, 14, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

### <a name='a10'></a> Maski logiczne

Pomocne zagadnienie w pracy z tablicami

In [194]:
A = np.arange(start=-10, stop=10, step=0.5)

In [195]:
A = np.arange(start=-10, stop=10, step=0.5)
A = A.reshape(10, -1)
A

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

Czym są maski logiczne? Jak możemy je tworzyć? Dlaczego są potrzebne w wycinaniu danych?

Gdybyśmy chcieli się dowiedzieć, w których miejscach mamy wartości ujemne, możemy sprawdzić to równaniem:

In [196]:
A > 0

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

To równanie zwraca nam maskę logiczną na tablicę. Zwróci prawdę, gdy mamy wartości większe od 0, fałsz - gdy są mniejsze. Dzięki takiej masce możemy wyciąć tylko te dane, które nas interesują.

Przekazując taką maskę do tablicy:

In [197]:
A[A>0]

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])

Dostajemy tylko te elementy, które są dodatnie, czyli tam, gdzie wartość wynosi True.

Możemy te elementy wycinać, dzięki takim operacjom. Ale możemy też łączyć dwa warunki i podać np. wartości w konkretnym przedziale, dzięki funkcji bitwise_and:

In [198]:
np.bitwise_and(A > -5, A < 5)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

Ten warunek zwróci nam konkretną maskę i prawdę, gdzie te oba warunki są spełnione.

Dzięki tej masce możemy wyciąć te elementy, które nas interesują, czyli elementy z przedziału -5, 5

In [199]:
A[np.bitwise_and(A > -5, A < 5)]

array([-4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,
        1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

Alternatywa - bitwise_or = możemy podać dwa warunki, np. A < -5, A > 5:

In [200]:
np.bitwise_or(A < -5, A > 5)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])